# Generated by Django 5.2.4 on 2025-09-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_date_of_birth_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
