# Generated by Django 5.2.5 on 2025-09-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_started_at', models.DateTimeField(auto_now_add=True)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('training_samples_count', models.PositiveIntegerField(default=0)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('precision_score', models.FloatField(blank=True, null=True)),
                ('recall_score', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='1.0', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Model Training Log',
                'verbose_name_plural': 'Model Training Logs',
                'ordering': ['-training_started_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Review text for training')),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Manually labeled sentiment', max_length=10)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sentiment Training Data',
                'verbose_name_plural': 'Sentiment Training Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(help_text='Sentiment score ranging from -1 (very negative) to 1 (very positive)')),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Predicted sentiment label', max_length=10)),
                ('confidence_score', models.FloatField(help_text='Confidence score of the prediction (0 to 1)')),
                ('positive_score', models.FloatField(default=0.0, help_text='Probability of positive sentiment')),
                ('negative_score', models.FloatField(default=0.0, help_text='Probability of negative sentiment')),
                ('neutral_score', models.FloatField(default=0.0, help_text='Probability of neutral sentiment')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewsentiment', to='store.review')),
            ],
            options={
                'verbose_name': 'Review Sentiment Analysis',
                'verbose_name_plural': 'Review Sentiment Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
